name:                data-sketches-core
version:             0.2.0.1
github:              "iand675/datasketches-haskell"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2021 Ian Duncan, Rob Bassi, Mercury Technologies"

default-extensions:
- BangPatterns
- FlexibleInstances
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- TypeOperators

extra-source-files:
- README.md
- ChangeLog.md
- cbits/req.h
- cbits/kll.h

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/datasketches-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq
- ghc-prim
- vector
- vector-algorithms
- primitive
- mwc-random

library:
  source-dirs: src
  c-sources:
  - cbits/sketches.c
  - cbits/kll.c
  - cbits/hll.c
  - cbits/countmin.c
  - cbits/theta.c
  - cbits/req.c
  include-dirs:
  - cbits
  cc-options:
  - -O2
  exposed-modules:
  - DataSketches.Core.Internal.URef
  - DataSketches.Core.Snapshot
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal.Auxiliary
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal.Compactor
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal.Constants
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal.DoubleBuffer
  - DataSketches.Quantiles.RelativeErrorQuantile.Internal.InequalitySearch
  - DataSketches.Quantiles.RelativeErrorQuantile.Types
  - DataSketches.Quantiles.KLL.Internal
  - DataSketches.Frequencies.CountMin.Internal
  - DataSketches.Distinct.HyperLogLog.Internal
  - DataSketches.Distinct.Theta.Internal
  - DataSketches.Core.Internal.CBindings
  - DataSketches.Quantiles.RelativeErrorQuantile.CInternal

tests:
  data-sketches-core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - data-sketches-core
